from __future__ import annotations

import asyncio
import base64
import hashlib
import os
import re
import shlex
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from typing import Any, Dict, List

import paramiko
from cryptography.fernet import Fernet, InvalidToken
from fastapi import APIRouter, Body, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from .db import get_db
from .master import TOKEN_SECRET, require_admin

router = APIRouter(prefix="/api/v1/master/servers", tags=["server-management"])
_executor = ThreadPoolExecutor(max_workers=4)
PJSIP_FILE = "/etc/asterisk/tccs-pjsip.conf"
EXTENSIONS_FILE = "/etc/asterisk/tccs-extensions.conf"
CONFBRIDGE_FILE = "/etc/asterisk/tccs-confbridge.conf"
PJSIP_MAIN = "/etc/asterisk/pjsip.conf"
EXTENSIONS_MAIN = "/etc/asterisk/extensions.conf"
CONFBRIDGE_MAIN = "/etc/asterisk/confbridge.conf"


def _fernet() -> Fernet:
    digest = hashlib.sha256(TOKEN_SECRET.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def _encrypt(value: str) -> str:
    return _fernet().encrypt(value.encode("utf-8")).decode("ascii")


def _decrypt(value: str) -> str:
    try:
        return _fernet().decrypt(value.encode("ascii")).decode("utf-8")
    except (InvalidToken, ValueError) as exc:
        raise HTTPException(500, "Stored server password cannot be decrypted; verify TCCS_ADMIN_TOKEN_SECRET") from exc


async def ensure_server_schema(db: AsyncSession) -> None:
    await db.execute(text("""
        CREATE TABLE IF NOT EXISTS asterisk_servers (
            id BIGSERIAL PRIMARY KEY,
            name VARCHAR(64) NOT NULL,
            role VARCHAR(16) NOT NULL DEFAULT 'PRIMARY',
            ip_address VARCHAR(64) NOT NULL UNIQUE,
            ssh_username VARCHAR(64) NOT NULL DEFAULT 'root',
            ssh_password_encrypted TEXT NOT NULL,
            ssh_port INTEGER NOT NULL DEFAULT 22,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            last_sync_at TIMESTAMPTZ,
            last_sync_status VARCHAR(32),
            last_sync_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """))
    await db.execute(text("CREATE INDEX IF NOT EXISTS idx_asterisk_servers_role ON asterisk_servers(role)"))
    await db.commit()


async def _query_config_data(db: AsyncSession) -> Dict[str, Any]:
    sections = [dict(r._mapping) for r in (await db.execute(text("SELECT id,code,name,enabled FROM sections ORDER BY id"))).all()]
    stations = [dict(r._mapping) for r in (await db.execute(text("SELECT id,station_number,name,location,section_id,sip_extension,station_type,enabled,priority FROM stations ORDER BY priority,station_number"))).all()]
    controllers = [dict(r._mapping) for r in (await db.execute(text("""
        SELECT c.id,c.code,c.name,c.section_id,c.enabled,c.sip_account_id,
               sa.extension AS sip_extension,sa.username AS sip_username,sa.password AS sip_password,
               sa.enabled AS sip_enabled
        FROM controllers c LEFT JOIN sip_accounts sa ON sa.id=c.sip_account_id
        ORDER BY c.code
    """))).all()]
    return {"sections": sections, "stations": stations, "controllers": controllers, "groups": []}


def _safe(value: Any) -> str:
    return str(value or "").replace("\n", " ").replace("\r", " ").strip()


def _generate_pjsip(data: Dict[str, Any]) -> str:
    lines = [
        "; TCCS MANAGED PJSIP CONFIGURATION", "; Generated by TCCS Server Management. Do not edit manually.",
        "; Generated at " + datetime.now(timezone.utc).isoformat(), "", "[transport-tccs]", "type=transport", "protocol=udp", "bind=0.0.0.0:5060", "",
        "[station-template](!)", "type=endpoint", "transport=transport-tccs", "context=tccs-stations", "disallow=all", "allow=alaw,ulaw", "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes", "",
        "[station-auth-template](!)", "type=auth", "auth_type=userpass", "", "[station-aor-template](!)", "type=aor", "max_contacts=1", "remove_existing=yes", "qualify_frequency=30", "",
    ]
    for station in data["stations"]:
        if not station["enabled"]: continue
        ext = _safe(station["sip_extension"])
        caller = f'{_safe(station["station_number"])} {_safe(station["name"])}'.strip()
        lines += [f"[{ext}](station-template)", f"aors={ext}", f"auth={ext}-auth", f'callerid="{caller}" <{ext}>', "", f"[{ext}-auth](station-auth-template)", f"username={ext}", f"password={ext}", "", f"[{ext}](station-aor-template)", ""]
    for controller in data["controllers"]:
        if not controller["enabled"] or not controller.get("sip_extension") or not controller.get("sip_enabled", True): continue
        ext = _safe(controller["sip_extension"]); username = _safe(controller.get("sip_username") or ext); password = _safe(controller.get("sip_password"))
        if not password: continue
        lines += [f"; Controller: {_safe(controller['code'])} - {_safe(controller['name'])}", f"[{ext}](station-template)", f"aors={ext}", f"auth={ext}-auth", f'callerid="{_safe(controller["name"])}" <{ext}>', "", f"[{ext}-auth](station-auth-template)", f"username={username}", f"password={password}", "", f"[{ext}](station-aor-template)", ""]
    return "\n".join(lines) + "\n"


def _generate_extensions(data: Dict[str, Any]) -> str:
    lines = [
        "; TCCS MANAGED DIALPLAN CONFIGURATION", "; Generated by TCCS Server Management. Do not edit manually.",
        "; Generated at " + datetime.now(timezone.utc).isoformat(), "", "[tccs-stations]",
        "exten => 900,1,NoOp(TCCS station joining ${TCCS_CONFERENCE})", " same => n,Answer()", " same => n,ExecIf($[\"${TCCS_CONFERENCE}\"=\"\"]?Hangup())", " same => n,ConfBridge(${TCCS_CONFERENCE},tccs_bridge,tccs_station)", " same => n,Hangup()", "",
        "exten => _10XX,1,NoOp(TCCS station call to ${EXTEN})", " same => n,Dial(PJSIP/${EXTEN},30)", " same => n,Hangup()", "",
    ]
    for controller in data["controllers"]:
        if not controller["enabled"] or not controller.get("sip_extension"): continue
        ext = _safe(controller["sip_extension"])
        lines += [f"; Controller {_safe(controller['code'])}: {ext}", f"exten => {ext},1,NoOp(TCCS station ${{CALLERID(num)}} joining controller {ext})", " same => n,Answer()", f" same => n,Set(TCCS_CONFERENCE=TCCS-CTRL-{ext})", " same => n,ConfBridge(${TCCS_CONFERENCE},tccs_bridge,tccs_station)", " same => n,Hangup()", ""]
    if not any(_safe(c.get("sip_extension")) == "9999" for c in data["controllers"]):
        lines += ["; Default Stage 2 browser controller conference entry", "exten => 9999,1,NoOp(TCCS browser controller joining SECTION01)", " same => n,Answer()", " same => n,ConfBridge(SECTION01,tccs_bridge,tccs_controller)", " same => n,Hangup()", ""]
    lines += ["; Direct station-to-controller dialing", "exten => _9XXX,1,NoOp(TCCS station ${CALLERID(num)} joining controller ${EXTEN})", " same => n,Answer()", " same => n,Set(TCCS_CONFERENCE=TCCS-CTRL-${EXTEN})", " same => n,ConfBridge(${TCCS_CONFERENCE},tccs_bridge,tccs_station)", " same => n,Hangup()", ""]
    return "\n".join(lines)


def _generate_confbridge(data: Dict[str, Any]) -> str:
    return "\n".join([
        "; TCCS MANAGED CONFBRIDGE CONFIGURATION", "; Generated by TCCS Server Management. Do not edit manually.", "; Generated at " + datetime.now(timezone.utc).isoformat(), "",
        "[tccs_bridge]", "type=bridge", "max_members=50", "record_conference=no", "record_file_append=no", "record_file_timestamp=yes", "",
        "[tccs_controller]", "type=user", "admin=yes", "marked=yes", "announce_only_user=no", "announce_user_count=no", "announce_user_count_all=no", "wait_marked=no", "end_marked=no", "quiet=no", "music_on_hold_when_empty=no", "",
        "[tccs_station]", "type=user", "admin=no", "marked=no", "announce_only_user=no", "announce_user_count=no", "announce_user_count_all=no", "wait_marked=no", "end_marked=no", "quiet=no", "music_on_hold_when_empty=no", "",
    ])


def _wait_shell(channel: paramiko.Channel, patterns: tuple[str, ...], timeout: float = 15.0) -> str:
    import time
    data = ""
    end = time.monotonic() + timeout
    while time.monotonic() < end:
        if channel.recv_ready():
            data += channel.recv(65535).decode("utf-8", "replace")
            low = data.lower()
            if any(p.lower() in low for p in patterns): return data
        else:
            time.sleep(0.1)
    raise RuntimeError("Timed out waiting for remote shell prompt")


def _open_root_shell(server: Dict[str, Any]) -> tuple[paramiko.SSHClient, paramiko.Channel]:
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(hostname=server["ip_address"], port=int(server.get("ssh_port") or 22), username=server["ssh_username"], password=_decrypt(server["ssh_password_encrypted"]), timeout=15, banner_timeout=15, auth_timeout=15, look_for_keys=False, allow_agent=False)
    channel = client.invoke_shell(width=200, height=50)
    _wait_shell(channel, ("$", "#", ">"))
    channel.send("sudo -i\n")
    response = _wait_shell(channel, ("password", "#"))
    if "password" in response.lower() and not re.search(r"(?:^|\n).*#\s*$", response):
        channel.send(_decrypt(server["ssh_password_encrypted"]) + "\n")
        response = _wait_shell(channel, ("#",), 15)
    channel.send("id -u\n")
    result = _wait_shell(channel, ("#",), 10)
    if not re.search(r"(?:^|\n)0(?:\s|\r?$)", result):
        channel.close(); client.close(); raise RuntimeError("sudo -i completed but root privileges were not confirmed")
    return client, channel


def _root_command(channel: paramiko.Channel, command: str, timeout: float = 30.0) -> str:
    channel.send(command.rstrip("\n") + "\n")
    return _wait_shell(channel, ("#",), timeout)


def _sync_remote(server: Dict[str, Any], files: Dict[str, str]) -> Dict[str, Any]:
    client, channel = _open_root_shell(server)
    try:
        for path, content in files.items():
            encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")
            cmd = f"mkdir -p /etc/asterisk && echo {shlex.quote(encoded)} | base64 -d > {shlex.quote(path)} && chmod 0640 {shlex.quote(path)}"
            _root_command(channel, cmd, 30)
        include_script = '''import os,sys,shutil,datetime\nparent,managed,label=sys.argv[1:]\nmarker='; BEGIN TCCS MANAGED INCLUDE '+label.upper()\nend='; END TCCS MANAGED INCLUDE '+label.upper()\ndata=open(parent).read() if os.path.exists(parent) else ''\nstart=data.find(marker)\nif start>=0:\n finish=data.find(end,start)\n if finish>=0:\n  finish += len(end)\n  while finish < len(data) and data[finish] in '\\r\\n': finish += 1\n  data=data[:start]+data[finish:]\nblock=marker+'\\n#include '+managed+'\\n'+end+'\\n'\ndata=data.rstrip()+'\\n\\n'+block\nbackup=parent+'.tccs-backup-'+datetime.datetime.now().strftime('%Y%m%d-%H%M%S')\nif os.path.exists(parent): shutil.copy2(parent,backup)\nopen(parent,'w').write(data)\nprint('UPDATED '+parent+' BACKUP '+backup)\n'''
        script64 = base64.b64encode(include_script.encode()).decode()
        for parent, managed, label in ((PJSIP_MAIN,PJSIP_FILE,"pjsip"),(EXTENSIONS_MAIN,EXTENSIONS_FILE,"extensions"),(CONFBRIDGE_MAIN,CONFBRIDGE_FILE,"confbridge")):
            cmd = f"echo {shlex.quote(script64)} | base64 -d | python3 - {shlex.quote(parent)} {shlex.quote(managed)} {shlex.quote(label)}"
            _root_command(channel, cmd, 30)
        for command in ("asterisk -rx 'pjsip reload'", "asterisk -rx 'dialplan reload'", "asterisk -rx 'module reload app_confbridge.so'"):
            _root_command(channel, command, 30)
        return {"status":"SYNCED", "message":f"TCCS configuration deployed to {server['ip_address']}"}
    finally:
        try: channel.close()
        finally: client.close()


async def _run_sync(server: Dict[str, Any], files: Dict[str, str]) -> Dict[str, Any]:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(_executor, _sync_remote, server, files)


def _test_root_access(server: Dict[str, Any]) -> Dict[str, Any]:
    client, channel = _open_root_shell(server)
    try:
        version = _root_command(channel, "asterisk -rx 'core show version'", 20)
        return {"status":"OK", "message":f"SSH login and sudo -i successful on {server['ip_address']}", "username":server["ssh_username"], "root":True, "asterisk":version.strip()}
    finally:
        try: channel.close()
        finally: client.close()


async def _run_test(server: Dict[str, Any]) -> Dict[str, Any]:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(_executor, _test_root_access, server)


@router.get("")
async def list_servers(db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db)
    result = await db.execute(text("SELECT id,name,role,ip_address,ssh_username,ssh_port,enabled,last_sync_at,last_sync_status,last_sync_message,created_at,updated_at FROM asterisk_servers ORDER BY CASE role WHEN 'PRIMARY' THEN 1 WHEN 'STANDBY' THEN 2 ELSE 3 END,name"))
    return [dict(r._mapping) for r in result.all()]


@router.post("")
async def create_server(payload: dict = Body(...), db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    name = _safe(payload.get("name")) or "Asterisk Server"
    role = _safe(payload.get("role")) or "PRIMARY"
    ip = _safe(payload.get("ip_address"))
    username = _safe(payload.get("ssh_username")) or "root"
    password = _safe(payload.get("ssh_password"))
    port = int(payload.get("ssh_port") or 22)
    if not ip or not password:
        raise HTTPException(400, "IP address and SSH password are required")
    await ensure_server_schema(db)
    try:
        result = await db.execute(text("INSERT INTO asterisk_servers (name,role,ip_address,ssh_username,ssh_password_encrypted,ssh_port,enabled) VALUES (:name,:role,:ip,:username,:password,:port,:enabled) RETURNING id"), {"name":name,"role":role,"ip":ip,"username":username,"password":_encrypt(password),"port":port,"enabled":bool(payload.get("enabled",True))})
        await db.commit()
        return {"id":result.scalar_one(),"status":"CREATED"}
    except Exception as exc:
        await db.rollback()
        raise HTTPException(400, str(exc)) from exc


@router.put("/{server_id}")
async def update_server(server_id: int, payload: dict = Body(...), db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db)
    row = (await db.execute(text("SELECT * FROM asterisk_servers WHERE id=:id"), {"id":server_id})).mappings().first()
    if row is None: raise HTTPException(404, "Asterisk server not found")
    fields=[]; params={"id":server_id}
    for key,col in (("name","name"),("role","role"),("ip_address","ip_address"),("ssh_username","ssh_username"),("ssh_port","ssh_port"),("enabled","enabled")):
        if key in payload:
            fields.append(f"{col}=:{key}"); params[key]=payload[key]
    if payload.get("ssh_password"):
        fields.append("ssh_password_encrypted=:ssh_password_encrypted"); params["ssh_password_encrypted"]=_encrypt(_safe(payload["ssh_password"]))
    if fields:
        fields.append("updated_at=NOW()")
        await db.execute(text(f"UPDATE asterisk_servers SET {','.join(fields)} WHERE id=:id"), params); await db.commit()
    return {"status":"UPDATED"}


@router.delete("/{server_id}")
async def delete_server(server_id: int, db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db)
    await db.execute(text("DELETE FROM asterisk_servers WHERE id=:id"), {"id":server_id}); await db.commit()
    return {"status":"DELETED"}


async def _get_server(db: AsyncSession, server_id: int) -> Dict[str, Any]:
    row=(await db.execute(text("SELECT * FROM asterisk_servers WHERE id=:id AND enabled=TRUE"),{"id":server_id})).mappings().first()
    if row is None: raise HTTPException(404,"Enabled Asterisk server not found")
    return dict(row)


@router.post("/{server_id}/test")
async def test_server(server_id: int, db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db); server=await _get_server(db,server_id)
    try: return await _run_test(server)
    except Exception as exc: raise HTTPException(502,f"Server connection failed: {exc}") from exc


@router.post("/{server_id}/sync")
async def sync_server(server_id: int, db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db); server=await _get_server(db,server_id); data=await _query_config_data(db)
    files={PJSIP_FILE:_generate_pjsip(data),EXTENSIONS_FILE:_generate_extensions(data),CONFBRIDGE_FILE:_generate_confbridge(data)}
    try:
        result=await _run_sync(server,files)
        await db.execute(text("UPDATE asterisk_servers SET last_sync_at=NOW(),last_sync_status=:status,last_sync_message=:message,updated_at=NOW() WHERE id=:id"),{"id":server_id,"status":result["status"],"message":result["message"]}); await db.commit(); return result
    except Exception as exc:
        await db.execute(text("UPDATE asterisk_servers SET last_sync_at=NOW(),last_sync_status='FAILED',last_sync_message=:message,updated_at=NOW() WHERE id=:id"),{"id":server_id,"message":str(exc)}); await db.commit()
        raise HTTPException(502,f"Server sync failed: {exc}") from exc


@router.post("/sync-all")
async def sync_all_servers(db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db)
    rows=(await db.execute(text("SELECT * FROM asterisk_servers WHERE enabled=TRUE ORDER BY id"))).mappings().all()
    data=await _query_config_data(db); files={PJSIP_FILE:_generate_pjsip(data),EXTENSIONS_FILE:_generate_extensions(data),CONFBRIDGE_FILE:_generate_confbridge(data)}
    results=[]
    for server in rows:
        try: results.append({"id":server["id"],**(await _run_sync(dict(server),files))})
        except Exception as exc: results.append({"id":server["id"],"status":"FAILED","message":str(exc)})
    return results


@router.get("/preview/config")
async def preview_config(db: AsyncSession = Depends(get_db), admin: dict = Depends(require_admin)):
    await ensure_server_schema(db); data=await _query_config_data(db)
    return {"pjsip":_generate_pjsip(data),"extensions":_generate_extensions(data),"confbridge":_generate_confbridge(data)}
