import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type State = 'ONLINE' | 'OFFLINE' | 'CALLING' | 'MUTED';
type ApiStation = { id: number; station_number: string; name: string; location: string | null; section_id: number; sip_extension: string; station_type: string; enabled: boolean; priority: number };
type EndpointStatus = { sip_extension: string; status: 'REGISTERED' | 'UNREGISTERED'; asterisk_state: string };
type Station = { id: string; dbId: number; name: string; state: State; sipExtension: string; location: string; priority: number; registered: boolean };
type Participant = { id: string; name: string; state: 'LISTENING' | 'MUTED' | 'TALKING' };
const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
function mapStation(s: ApiStation): Station { return { id: s.station_number, dbId: s.id, name: s.name, state: 'ONLINE', sipExtension: s.sip_extension, location: s.location || '', priority: s.priority, registered: false }; }
function App() {
 const [stations,setStations]=useState<Station[]>([]); const [loading,setLoading]=useState(true); const [apiError,setApiError]=useState<string|null>(null); const [participants,setParticipants]=useState<Participant[]>([]); const [modal,setModal]=useState<string|null>(null); const [message,setMessage]=useState('Connecting to TCCS Controller API...'); const [draggedId,setDraggedId]=useState<string|null>(null); const [layoutEdit,setLayoutEdit]=useState(false); const [layoutSaving,setLayoutSaving]=useState(false); const online=useMemo(()=>stations.filter(s=>s.registered).length,[stations]);
 const loadStations=async()=>{setLoading(true);setApiError(null);try{const response=await fetch(`${API_BASE}/api/v1/stations`);if(!response.ok)throw new Error(`API returned HTTP ${response.status}`);const data:ApiStation[]=await response.json();setStations(data.map(mapStation).sort((a,b)=>a.priority-b.priority));setMessage(`Connected • ${data.length} stations loaded`);}catch(error){const text=error instanceof Error?error.message:'Unable to reach API';setApiError(text);setMessage('Controller API unavailable');}finally{setLoading(false);}};
 const refreshEndpointStatus=async()=>{try{const response=await fetch(`${API_BASE}/api/v1/asterisk/endpoints`);if(!response.ok)throw new Error(`Asterisk API HTTP ${response.status}`);const data:EndpointStatus[]=await response.json();const registered=new Set(data.filter(e=>e.status==='REGISTERED').map(e=>e.sip_extension));setStations(current=>current.map(s=>({...s,registered:registered.has(s.sipExtension),state:s.state==='CALLING'||s.state==='MUTED'?s.state:(registered.has(s.sipExtension)?'ONLINE':'OFFLINE')})));setApiError(null);}catch(error){setApiError(error instanceof Error?error.message:'Unable to read Asterisk status');}};
 useEffect(()=>{loadStations();},[]); useEffect(()=>{if(!stations.length)return;refreshEndpointStatus();const timer=window.setInterval(refreshEndpointStatus,3000);return()=>window.clearInterval(timer);},[stations.length]);
 const beginLayoutEdit=()=>{setLayoutEdit(true);setMessage('Station layout edit mode enabled • drag stations to reorder');};
 const cancelLayoutEdit=()=>{setLayoutEdit(false);setDraggedId(null);loadStations();setMessage('Station layout changes discarded');};
 const reorderStations=(fromId:string,toId:string)=>{if(!layoutEdit||fromId===toId)return;setStations(current=>{const next=[...current];const fromIndex=next.findIndex(s=>s.id===fromId);const toIndex=next.findIndex(s=>s.id===toId);if(fromIndex<0||toIndex<0)return current;const [moved]=next.splice(fromIndex,1);next.splice(toIndex,0,moved);return next.map((s,index)=>({...s,priority:(index+1)*10}));});setMessage(`Station ${fromId} moved before station ${toId}`);};
 const saveLayout=async()=>{setLayoutSaving(true);try{const response=await fetch(`${API_BASE}/api/v1/stations/order`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({station_ids:stations.map(s=>s.dbId)})});if(!response.ok){const detail=await response.text();throw new Error(detail||`API returned HTTP ${response.status}`);}setLayoutEdit(false);setDraggedId(null);setMessage('Station layout saved successfully');await loadStations();}catch(error){setMessage(`Layout save failed: ${error instanceof Error?error.message:'Unable to save station layout'}`);}finally{setLayoutSaving(false);}};
 const callStation=(station:Station)=>{if(station.state==='OFFLINE'){setMessage(`Station ${station.id} is unregistered`);return;}setParticipants(current=>current.some(p=>p.id===station.id)?current:[...current,{id:station.id,name:station.name,state:'LISTENING'}]);setStations(current=>current.map(s=>s.id===station.id?{...s,state:'CALLING'}:s));setMessage(`Calling station ${station.id} • automatically added to active conference`);};
 const addParticipant=(station:Station)=>{if(!station.registered)return setMessage(`Station ${station.id} is unregistered`);setParticipants(current=>current.some(p=>p.id===station.id)?current:[...current,{id:station.id,name:station.name,state:'LISTENING'}]);setMessage(`Station ${station.id} added to conference`);setModal(null);};
 const generalCall=()=>{setParticipants(stations.filter(s=>s.registered).map(s=>({id:s.id,name:s.name,state:'LISTENING'})));setMessage('General call prepared for all registered stations');};
 const toggleMute=(id:string)=>{setParticipants(current=>current.map(p=>p.id===id?{...p,state:p.state==='MUTED'?'LISTENING':'MUTED'}:p));const participant=participants.find(p=>p.id===id);setMessage(`${participant?.name||`Station ${id}`} ${participant?.state==='MUTED'?'unmuted':'muted'}`);};
 const remove=(id:string)=>{setParticipants(current=>current.filter(p=>p.id!==id));setStations(current=>current.map(s=>s.id===id?{...s,state:s.registered?'ONLINE':'OFFLINE'}:s));setMessage(`Station ${id} removed from conference`);};
 return <div className="app"><header className="topbar"><div><div className="brand">TCCS</div><div className="subtitle">Train Control Communication System</div></div><div className="top-status"><span>SECTION <b>01</b></span><span>CONTROLLER <b>C01</b></span><span className={apiError?'error':'ok'}>● {apiError?'API OFFLINE':loading?'CONNECTING':'SYSTEM NORMAL'}</span></div></header><main><div className="heading"><div><h1>Controller Console</h1><p>Stage 2 • Controller UI • Live Asterisk Status</p></div><div className="toolbar"><button onClick={()=>setModal('directory')}>Directory</button><button onClick={()=>setModal('history')}>Call History</button><button onClick={()=>setModal('settings')}>Settings</button></div></div>{apiError&&<div className="api-error"><b>Controller/Asterisk status unavailable.</b> {apiError} <button onClick={loadStations}>RETRY</button></div>}
 <div className="console-grid"><section className="panel stations-panel"><div className="section-title"><div className="title-with-actions"><h2>Way Stations</h2><div className="layout-actions">{!layoutEdit?<button className="icon-button" onClick={beginLayoutEdit} title="Edit station layout" aria-label="Edit station layout">✎</button>:<><button className="icon-button save-layout" onClick={saveLayout} disabled={layoutSaving} title="Save station layout" aria-label="Save station layout">{layoutSaving?'…':'✓'}</button><button className="icon-button cancel-layout" onClick={cancelLayoutEdit} disabled={layoutSaving} title="Cancel layout changes" aria-label="Cancel layout changes">×</button></>}</div></div><span>{loading?'Loading...':layoutEdit?'EDIT MODE • Drag stations to reorder':`${online}/${stations.length} registered`}</span></div>{loading?<div className="empty">Loading station configuration from PostgreSQL...</div>:stations.length===0?<div className="empty">No enabled stations configured</div>:<div className="station-grid">{stations.map(s=><button key={s.id} draggable={layoutEdit} className={`station ${s.state.toLowerCase()} ${draggedId===s.id?'dragging':''} ${layoutEdit?'layout-edit':''}`} onDragStart={e=>{if(!layoutEdit){e.preventDefault();return;}setDraggedId(s.id);}} onDragEnd={()=>setDraggedId(null)} onDragOver={e=>{if(layoutEdit)e.preventDefault();}} onDrop={()=>{if(layoutEdit&&draggedId)reorderStations(draggedId,s.id);setDraggedId(null);}} onClick={()=>{if(!layoutEdit)callStation(s);}} title={layoutEdit?`Drag ${s.name} to reorder`:`${s.registered?'Call':'Station unregistered'} ${s.name}`}>{layoutEdit&&<span className="drag-handle" aria-hidden="true">⋮⋮</span>}<strong>{s.id}</strong><small>{s.name}</small><span>● {s.registered?'REGISTERED':'UNREGISTERED'}</span></button>)}</div>}</section>
 <section className="panel conference-panel"><div className="section-title"><h2>Active Conference</h2><span>{participants.length?`${participants.length} participant(s)`:'No active conference'}</span></div>{participants.length===0?<div className="empty">No active participants</div>:<div className="conference-table"><div className="conference-head"><span>STATION</span><span>NAME</span><span>STATUS</span><span>ACTION</span></div>{participants.map(p=><div className="participant" key={p.id}><b>{p.id}</b><span>{p.name}</span><span className="participant-state">● {p.state}</span><div className="participant-actions"><button className={p.state==='MUTED'?'muted-action':''} onClick={()=>toggleMute(p.id)}>{p.state==='MUTED'?'UNMUTE':'MUTE'}</button><button className="hangup-action" onClick={()=>remove(p.id)}>HANG UP</button></div></div>)}</div>}</section></div>
 <div className="call-actions"><button className="primary" onClick={generalCall} disabled={!online||layoutEdit}>GENERAL CALL</button><button onClick={generalCall} disabled={!online||layoutEdit}>SECTION CALL</button><button onClick={()=>setModal('group')} disabled={layoutEdit}>GROUP CALL</button><button onClick={()=>setModal('add')} disabled={!stations.length||layoutEdit}>ADD SUBSCRIBER</button></div><div className="bottom-actions"><button onClick={()=>setMessage('Hold control selected')} disabled={layoutEdit}>Hold</button><button onClick={()=>setMessage('Transfer control selected')} disabled={layoutEdit}>Transfer</button><button onClick={()=>setModal('recordings')} disabled={layoutEdit}>Recordings</button><button onClick={()=>setModal('diagnostics')} disabled={layoutEdit}>Diagnostics</button><button className="emergency" onClick={()=>setModal('emergency')} disabled={layoutEdit}>Emergency</button></div><div className="statusbar">{message}</div></main>{modal&&<Modal modal={modal} stations={stations} onClose={()=>setModal(null)} onAdd={addParticipant}/>}</div>;
}
function Modal({modal,stations,onClose,onAdd}:{modal:string;stations:Station[];onClose:()=>void;onAdd:(s:Station)=>void}){if(modal==='add')return <Overlay title="Add Subscriber" onClose={onClose}><p>Select a registered station.</p><div className="modal-list">{stations.map(s=><button key={s.id} disabled={!s.registered} onClick={()=>onAdd(s)}>{s.id} — {s.name} — {s.registered?'REGISTERED':'UNREGISTERED'}</button>)}</div></Overlay>;if(modal==='directory')return <Overlay title="Directory" onClose={onClose}><div className="modal-list">{stations.map(s=><button key={s.id}>{s.id} — {s.name} — {s.registered?'REGISTERED':'UNREGISTERED'}</button>)}</div></Overlay>;if(modal==='group')return <Overlay title="Group Call" onClose={onClose}><p>Configured groups will be loaded from PostgreSQL in the backend phase.</p><div className="modal-list"><button onClick={onClose}>SECTION 01 GROUP</button></div></Overlay>;if(modal==='emergency')return <Overlay title="Emergency Call" onClose={onClose}><p><b>TEST MODE:</b> no emergency call is transmitted by this prototype.</p><p>The production implementation will connect this control to the validated emergency communication workflow.</p><button className="emergency" onClick={onClose}>ACTIVATE TEST</button></Overlay>;const labels:Record<string,string>={history:'Call History',settings:'Settings',recordings:'Recordings',diagnostics:'Diagnostics'};return <Overlay title={labels[modal]||'TCCS'} onClose={onClose}><p>This function is reserved for the backend integration phase.</p></Overlay>}
function Overlay({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><h3>{title}</h3>{children}<div className="modal-footer"><button onClick={onClose}>Close</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
